server:
  servlet:
    context-path: /enterprise

spring:
  security:
    cors:
      allowed:
        origins: http://localhost:4200
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/idp
  application:
    name: enterprise
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/sep490_enterprise?serverTimezone=UTC
    username: postgres
    password: postgres
  flyway:
    output-query-results: true
    create-schemas: false
    clean-disabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        query:
          fail_on_pagination_over_collection_fetch: true
  kafka:
    admin:
      fail-fast: true
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      auto-offset-reset: latest
      group-id: sep490-enterprise
  mail:
    host: 127.0.0.1
    port: 1025
    username:
    password:
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: false
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket:
    name: sep490-files

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

payment:
  payos:
    client_id: not_a_real_key_to_prevent_null
    api_key: not_a_real_key_to_prevent_null
    checksum_key: not_a_real_key_to_prevent_null
    returnPath: /enterprise/payment
    cancelPath: /enterprise/payment

exchangerate-api:
  key: secret_key_to_prevent_null
  url: https://v6.exchangerate-api.com/v6/

geocoding:
  key: secret_key_to_prevent_null
  url: https://geocode.maps.co/reverse