version: "3.9"
services:
  database:
    image: postgres:17.0
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: spoteaseDB
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "spoteaseDB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - spotease-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - spotease-network

  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - spotease-network

  mail:
    image: mailhog/mailhog
    container_name: mailhog
    profiles:
      - dev
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - spotease-network

  minio:
    image: quay.io/minio/minio
    container_name: minio
    profiles:
      - dev
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ../miniodata:/data
    command: server /data --console-address ":9001"


networks:
    spotease-network:
      driver: bridge
volumes:
  spotease-data:
