/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AddressSuggestionDTO {
  displayName?: string;
  road?: string;
  quarter?: string;
  suburb?: string;
  city?: string;
  postcode?: string;
  country?: string;
  countryCode?: string;
}
