/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {AssetBuildingView} from './asset-building-view';

export interface AssetView {
  id?: string;
  version?: number;
  name?: string;
  code?: string;
  description?: string;
  building?: AssetBuildingView;
}
