/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {TenantDTO} from './tenant-dto';
import {BuildingDTO} from './building-dto';
import {EmissionActivityDTO} from './emission-activity-dto';

export interface BuildingGroupDTO {
  id?: string;
  version?: number;
  name?: string;
  description?: string;
  building?: BuildingDTO;
  tenant?: TenantDTO;
  emissionActivities?: Set<EmissionActivityDTO>;
}
