/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {BuildingGroupView} from './building-group-view';

export interface BuildingView {
  id?: string;
  name?: string;
  buildingGroup?: BuildingGroupView;
}
