/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {SubscriptionDTO} from './subscription-dto';

export interface BuildingDTO {
  id?: string;
  version?: number;
  name?: string;
  address?: string;
  numberOfLevels?: number;
  area?: number;
  latitude?: number;
  longitude?: number;
  subscriptionDTO?: SubscriptionDTO;
  limit?: number;
}
