/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ChemicalDensityDTO {
  id?: string;
  version?: number;
  chemicalFormula?: string;
  value?: number;
  unitNumerator: ChemicalDensityDTO.UnitNumeratorEnum;
  unitDenominator: ChemicalDensityDTO.UnitDenominatorEnum;
}
export namespace ChemicalDensityDTO {
  export const UnitNumeratorEnum = {
    GRAM: 'GRAM',
    KILOGRAM: 'KILOGRAM',
    MEGAGRAM: 'MEGAGRAM',
    GIGAGRAM: 'GIGAGRAM',
    TERAGRAM: 'TERAGRAM',
    MILLILITER: 'MILLILITER',
    CENTILITER: 'CENTILITER',
    DECILITER: 'DECILITER',
    LITER: 'LITER',
    CUBIC_METER: 'CUBIC_METER',
    UK_GALLON: 'UK_GALLON',
    US_GALLON: 'US_GALLON',
    BARREL: 'BARREL',
    PECK: 'PECK',
    THOUSAND_CUBIC_METER: 'THOUSAND_CUBIC_METER',
    MILLION_CUBIC_METER: 'MILLION_CUBIC_METER',
    WH: 'WH',
    KWH: 'KWH',
    TERAJOULE: 'TERAJOULE',
    GIGAJOULE: 'GIGAJOULE',
    MEGAJOULE: 'MEGAJOULE',
    PERCENT: 'PERCENT',
    PIECES: 'PIECES'
  } as const;
  export type UnitNumeratorEnum = (typeof UnitNumeratorEnum)[keyof typeof UnitNumeratorEnum];
  export const UnitDenominatorEnum = {
    GRAM: 'GRAM',
    KILOGRAM: 'KILOGRAM',
    MEGAGRAM: 'MEGAGRAM',
    GIGAGRAM: 'GIGAGRAM',
    TERAGRAM: 'TERAGRAM',
    MILLILITER: 'MILLILITER',
    CENTILITER: 'CENTILITER',
    DECILITER: 'DECILITER',
    LITER: 'LITER',
    CUBIC_METER: 'CUBIC_METER',
    UK_GALLON: 'UK_GALLON',
    US_GALLON: 'US_GALLON',
    BARREL: 'BARREL',
    PECK: 'PECK',
    THOUSAND_CUBIC_METER: 'THOUSAND_CUBIC_METER',
    MILLION_CUBIC_METER: 'MILLION_CUBIC_METER',
    WH: 'WH',
    KWH: 'KWH',
    TERAJOULE: 'TERAJOULE',
    GIGAJOULE: 'GIGAJOULE',
    MEGAJOULE: 'MEGAJOULE',
    PERCENT: 'PERCENT',
    PIECES: 'PIECES'
  } as const;
  export type UnitDenominatorEnum = (typeof UnitDenominatorEnum)[keyof typeof UnitDenominatorEnum];
}
