/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {EmissionActivityRecordDTO} from './emission-activity-record-dto';

export interface CreateEmissionActivityDTO {
  id?: string;
  version?: number;
  buildingId: string;
  buildingGroupID?: string;
  records?: Set<EmissionActivityRecordDTO>;
  emissionFactorID: string;
  name?: string;
  type?: string;
  category?: string;
  description?: string;
}
