/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {NewEmissionActivityRecordDTO} from './new-emission-activity-record-dto';

export interface CreateRecordRequest {
  record: NewEmissionActivityRecordDTO;
  file?: Blob;
}
