/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreditConvertRatioDTO {
  id?: string;
  version?: number;
  ratio?: number;
  convertType?: CreditConvertRatioDTO.ConvertTypeEnum;
}
export namespace CreditConvertRatioDTO {
  export const ConvertTypeEnum = {
    MONTH: 'MONTH',
    DEVICE: 'DEVICE'
  } as const;
  export type ConvertTypeEnum = (typeof ConvertTypeEnum)[keyof typeof ConvertTypeEnum];
}
