/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {BuildingGhgEmission} from './building-ghg-emission';
import {DistributionEmissionSource} from './distribution-emission-source';

export interface DefaultChartView {
  totalEnterpriseEmissions?: number;
  distributionEmissionSources?: DistributionEmissionSource[];
  buildingGhgEmissions?: BuildingGhgEmission[];
}
