/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {ActivityTypeDTO} from './activity-type-dto';
import {EmissionActivityRecordDTO} from './emission-activity-record-dto';

export interface EmissionActivityDTO {
  id?: string;
  version?: number;
  buildingGroupID: string;
  records?: Set<EmissionActivityRecordDTO>;
  emissionFactorID: string;
  name?: string;
  type?: ActivityTypeDTO;
  category?: string;
  description?: string;
}
