/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EmissionActivityGhg {
  name?: string;
  category?: string;
  typeName?: string;
  buildingName?: string;
  buildingGroupName?: string;
  tenantName?: string;
  factorNameVN?: string;
  factorNameEN?: string;
  factorNameZH?: string;
  factorValidFrom?: string;
  factorValidTo?: string;
  sourceNameVN?: string;
  sourceNameEN?: string;
  sourceNameZH?: string;
  ghg?: number;
}
