/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {EmissionSourceDTO} from './emission-source-dto';
import {EnergyConversionDTO} from './energy-conversion-dto';

export interface EmissionFactorDTO {
  id?: string;
  version?: number;
  co2?: number;
  ch4?: number;
  n2o?: number;
  nameVN?: string;
  nameEN?: string;
  nameZH?: string;
  emissionUnitNumerator?: EmissionFactorDTO.EmissionUnitNumeratorEnum;
  emissionUnitDenominator?: EmissionFactorDTO.EmissionUnitDenominatorEnum;
  emissionSourceDTO?: EmissionSourceDTO;
  description?: string;
  validFrom?: string;
  validTo?: string;
  directEmission?: boolean;
  energyConversionDTO?: EnergyConversionDTO;
  active?: boolean;
}
export namespace EmissionFactorDTO {
  export const EmissionUnitNumeratorEnum = {
    GRAM: 'GRAM',
    KILOGRAM: 'KILOGRAM',
    MEGAGRAM: 'MEGAGRAM',
    GIGAGRAM: 'GIGAGRAM',
    TERAGRAM: 'TERAGRAM',
    MILLILITER: 'MILLILITER',
    CENTILITER: 'CENTILITER',
    DECILITER: 'DECILITER',
    LITER: 'LITER',
    CUBIC_METER: 'CUBIC_METER',
    UK_GALLON: 'UK_GALLON',
    US_GALLON: 'US_GALLON',
    BARREL: 'BARREL',
    PECK: 'PECK',
    THOUSAND_CUBIC_METER: 'THOUSAND_CUBIC_METER',
    MILLION_CUBIC_METER: 'MILLION_CUBIC_METER',
    WH: 'WH',
    KWH: 'KWH',
    TERAJOULE: 'TERAJOULE',
    GIGAJOULE: 'GIGAJOULE',
    MEGAJOULE: 'MEGAJOULE',
    PERCENT: 'PERCENT',
    PIECES: 'PIECES'
  } as const;
  export type EmissionUnitNumeratorEnum =
    (typeof EmissionUnitNumeratorEnum)[keyof typeof EmissionUnitNumeratorEnum];
  export const EmissionUnitDenominatorEnum = {
    GRAM: 'GRAM',
    KILOGRAM: 'KILOGRAM',
    MEGAGRAM: 'MEGAGRAM',
    GIGAGRAM: 'GIGAGRAM',
    TERAGRAM: 'TERAGRAM',
    MILLILITER: 'MILLILITER',
    CENTILITER: 'CENTILITER',
    DECILITER: 'DECILITER',
    LITER: 'LITER',
    CUBIC_METER: 'CUBIC_METER',
    UK_GALLON: 'UK_GALLON',
    US_GALLON: 'US_GALLON',
    BARREL: 'BARREL',
    PECK: 'PECK',
    THOUSAND_CUBIC_METER: 'THOUSAND_CUBIC_METER',
    MILLION_CUBIC_METER: 'MILLION_CUBIC_METER',
    WH: 'WH',
    KWH: 'KWH',
    TERAJOULE: 'TERAJOULE',
    GIGAJOULE: 'GIGAJOULE',
    MEGAJOULE: 'MEGAJOULE',
    PERCENT: 'PERCENT',
    PIECES: 'PIECES'
  } as const;
  export type EmissionUnitDenominatorEnum =
    (typeof EmissionUnitDenominatorEnum)[keyof typeof EmissionUnitDenominatorEnum];
}
