/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {RecordFileView} from './record-file-view';

export interface EmissionActivityRecordView {
  id?: string;
  version?: number;
  ghg?: number;
  value?: number;
  unit?: EmissionActivityRecordView.UnitEnum;
  startDate?: string;
  endDate?: string;
  file?: RecordFileView;
  quantity?: number;
}
export namespace EmissionActivityRecordView {
  export const UnitEnum = {
    GRAM: 'GRAM',
    KILOGRAM: 'KILOGRAM',
    MEGAGRAM: 'MEGAGRAM',
    GIGAGRAM: 'GIGAGRAM',
    TERAGRAM: 'TERAGRAM',
    MILLILITER: 'MILLILITER',
    CENTILITER: 'CENTILITER',
    DECILITER: 'DECILITER',
    LITER: 'LITER',
    CUBIC_METER: 'CUBIC_METER',
    UK_GALLON: 'UK_GALLON',
    US_GALLON: 'US_GALLON',
    BARREL: 'BARREL',
    PECK: 'PECK',
    THOUSAND_CUBIC_METER: 'THOUSAND_CUBIC_METER',
    MILLION_CUBIC_METER: 'MILLION_CUBIC_METER',
    WH: 'WH',
    KWH: 'KWH',
    TERAJOULE: 'TERAJOULE',
    GIGAJOULE: 'GIGAJOULE',
    MEGAJOULE: 'MEGAJOULE',
    PERCENT: 'PERCENT',
    PIECES: 'PIECES'
  } as const;
  export type UnitEnum = (typeof UnitEnum)[keyof typeof UnitEnum];
}
