/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EmissionActivityView {
  id?: string;
  version?: number;
  building?: string;
  emissionFactor?: string;
  type?: string;
  name?: string;
  category?: string;
  description?: string;
}
