/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {EmissionActivityBuildingGroupView} from './emission-activity-building-group-view';
import {EmissionActivityBuildingView} from './emission-activity-building-view';
import {EmissionActivityFactorView} from './emission-activity-factor-view';
import {EmissionActivityRecordView} from './emission-activity-record-view';

export interface EmissionActivityView {
  id?: string;
  version?: number;
  building?: EmissionActivityBuildingView;
  buildingGroup?: EmissionActivityBuildingGroupView;
  emissionFactor?: EmissionActivityFactorView;
  type?: string;
  name?: string;
  category?: string;
  description?: string;
  records?: EmissionActivityRecordView[];
}
