/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {FuelDTO} from './fuel-dto';

export interface EnergyConversionDTO {
  id?: string;
  fuel?: FuelDTO;
  conversionValue?: number;
  conversionUnitNumerator?: EnergyConversionDTO.ConversionUnitNumeratorEnum;
  conversionUnitDenominator?: EnergyConversionDTO.ConversionUnitDenominatorEnum;
  version?: number;
}
export namespace EnergyConversionDTO {
  export const ConversionUnitNumeratorEnum = {
    GRAM: 'GRAM',
    KILOGRAM: 'KILOGRAM',
    MEGAGRAM: 'MEGAGRAM',
    GIGAGRAM: 'GIGAGRAM',
    TERAGRAM: 'TERAGRAM',
    MILLILITER: 'MILLILITER',
    CENTILITER: 'CENTILITER',
    DECILITER: 'DECILITER',
    LITER: 'LITER',
    CUBIC_METER: 'CUBIC_METER',
    UK_GALLON: 'UK_GALLON',
    US_GALLON: 'US_GALLON',
    BARREL: 'BARREL',
    PECK: 'PECK',
    THOUSAND_CUBIC_METER: 'THOUSAND_CUBIC_METER',
    MILLION_CUBIC_METER: 'MILLION_CUBIC_METER',
    WH: 'WH',
    KWH: 'KWH',
    TERAJOULE: 'TERAJOULE',
    GIGAJOULE: 'GIGAJOULE',
    MEGAJOULE: 'MEGAJOULE',
    PERCENT: 'PERCENT',
    PIECES: 'PIECES'
  } as const;
  export type ConversionUnitNumeratorEnum =
    (typeof ConversionUnitNumeratorEnum)[keyof typeof ConversionUnitNumeratorEnum];
  export const ConversionUnitDenominatorEnum = {
    GRAM: 'GRAM',
    KILOGRAM: 'KILOGRAM',
    MEGAGRAM: 'MEGAGRAM',
    GIGAGRAM: 'GIGAGRAM',
    TERAGRAM: 'TERAGRAM',
    MILLILITER: 'MILLILITER',
    CENTILITER: 'CENTILITER',
    DECILITER: 'DECILITER',
    LITER: 'LITER',
    CUBIC_METER: 'CUBIC_METER',
    UK_GALLON: 'UK_GALLON',
    US_GALLON: 'US_GALLON',
    BARREL: 'BARREL',
    PECK: 'PECK',
    THOUSAND_CUBIC_METER: 'THOUSAND_CUBIC_METER',
    MILLION_CUBIC_METER: 'MILLION_CUBIC_METER',
    WH: 'WH',
    KWH: 'KWH',
    TERAJOULE: 'TERAJOULE',
    GIGAJOULE: 'GIGAJOULE',
    MEGAJOULE: 'MEGAJOULE',
    PERCENT: 'PERCENT',
    PIECES: 'PIECES'
  } as const;
  export type ConversionUnitDenominatorEnum =
    (typeof ConversionUnitDenominatorEnum)[keyof typeof ConversionUnitDenominatorEnum];
}
