/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EnterpriseDetailDTO {
  id?: string;
  version?: number;
  name?: string;
  enterpriseEmail?: string;
  hotline?: string;
  address?: string;
  taxCode?: string;
  businessLicenseImageUrl?: string;
  representativeName?: string;
  representativePosition?: string;
  representativeContact?: string;
}
