/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {BuildingPermissionDTO} from './building-permission-dto';

export interface EnterpriseUserDetailsDTO {
  id?: string;
  version?: number;
  createdDate?: string;
  email?: string;
  phone?: string;
  emailVerified?: boolean;
  firstName?: string;
  lastName?: string;
  role: EnterpriseUserDetailsDTO.RoleEnum;
  scope: EnterpriseUserDetailsDTO.ScopeEnum;
  buildingPermissions?: BuildingPermissionDTO[];
}
export namespace EnterpriseUserDetailsDTO {
  export const RoleEnum = {
    BASIC_USER: 'BASIC_USER',
    TENANT: 'TENANT',
    ENTERPRISE_OWNER: 'ENTERPRISE_OWNER',
    SYSTEM_ADMIN: 'SYSTEM_ADMIN'
  } as const;
  export type RoleEnum = (typeof RoleEnum)[keyof typeof RoleEnum];
  export const ScopeEnum = {
    BUILDING: 'BUILDING',
    ENTERPRISE: 'ENTERPRISE'
  } as const;
  export type ScopeEnum = (typeof ScopeEnum)[keyof typeof ScopeEnum];
}
