/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EnterpriseDTO {
  id?: string;
  version?: number;
  name?: string;
  email?: string;
  hotline?: string;
}
