/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EnterpriseUserDTO {
  id?: string;
  name?: string;
  email?: string;
  role: EnterpriseUserDTO.RoleEnum;
  emailVerified?: boolean;
}
export namespace EnterpriseUserDTO {
  export const RoleEnum = {
    BASIC_USER: 'BASIC_USER',
    TENANT: 'TENANT',
    ENTERPRISE_OWNER: 'ENTERPRISE_OWNER',
    SYSTEM_ADMIN: 'SYSTEM_ADMIN'
  } as const;
  export type RoleEnum = (typeof RoleEnum)[keyof typeof RoleEnum];
}
