/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FuelDTO {
  id?: string;
  nameVN?: string;
  nameEN?: string;
  nameZH?: string;
  version?: number;
}
