/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {CreditPackageVersionDTO} from './credit-package-version-dto';

export interface GetCreditPackageDTOAdmin {
  id?: string;
  version?: number;
  numberOfCredits?: number;
  price?: number;
  active?: boolean;
  packageVersionDTOList?: CreditPackageVersionDTO[];
}
