/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface InvitationSearchCriteria {
  enterpriseId: string;
  buildingId?: string;
  buildingGroupId?: string;
  tenantEmail?: string;
  status?: InvitationSearchCriteria.StatusEnum;
}
export namespace InvitationSearchCriteria {
  export const StatusEnum = {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED'
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
}
