/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {BuildingGroupDTO} from './building-group-dto';

export interface InvitationDTO {
  id?: string;
  email?: string;
  version?: number;
  status?: InvitationDTO.StatusEnum;
  buildingGroup?: BuildingGroupDTO;
}
export namespace InvitationDTO {
  export const StatusEnum = {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED'
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
}
