/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface NumberOfTransactionByType {
  type?: NumberOfTransactionByType.TypeEnum;
  count?: number;
}
export namespace NumberOfTransactionByType {
  export const TypeEnum = {
    NEW_PURCHASE: 'NEW_PURCHASE',
    UPGRADE: 'UPGRADE'
  } as const;
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
}
