/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PaymentEnterpriseAdminDTO {
  id?: string;
  version?: number;
  enterpriseName?: string;
  createdDate?: string;
  numberOfCredits?: number;
  status?: PaymentEnterpriseAdminDTO.StatusEnum;
}
export namespace PaymentEnterpriseAdminDTO {
  export const StatusEnum = {
    PENDING: 'PENDING',
    PAID: 'PAID',
    PROCESSING: 'PROCESSING',
    CANCELLED: 'CANCELLED'
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
}
