/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PowerBiAuthorityDTO {
  id?: string;
  version?: number;
  note?: string;
  expirationTime: string;
  scope: PowerBiAuthorityDTO.ScopeEnum;
  buildings?: Set<string>;
  lastUsed?: string;
}
export namespace PowerBiAuthorityDTO {
  export const ScopeEnum = {
    BUILDING: 'BUILDING',
    ENTERPRISE: 'ENTERPRISE'
  } as const;
  export type ScopeEnum = (typeof ScopeEnum)[keyof typeof ScopeEnum];
}
