/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RegisterEnterpriseDTO {
  name?: string;
  enterpriseEmail?: string;
  taxCode?: string;
  hotline?: string;
  role: RegisterEnterpriseDTO.RoleEnum;
  address?: string;
  businessLicenseImageUrl?: string;
  representativeName?: string;
  representativePosition?: string;
  representativeContact?: string;
}
export namespace RegisterEnterpriseDTO {
  export const RoleEnum = {
    BASIC_USER: 'BASIC_USER',
    TENANT: 'TENANT',
    ENTERPRISE_OWNER: 'ENTERPRISE_OWNER',
    SYSTEM_ADMIN: 'SYSTEM_ADMIN'
  } as const;
  export type RoleEnum = (typeof RoleEnum)[keyof typeof RoleEnum];
}
