/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PaymentRevenueByQuarter} from './payment-revenue-by-quarter';
import {NumberOfTransactionByType} from './number-of-transaction-by-type';

export interface RevenueReportDTO {
  numberOfPaidPayment?: number;
  totalRevenue?: number;
  numberOfTransactions?: number;
  revenueByQuarter?: {[key: string]: PaymentRevenueByQuarter};
  numberOfTransactionByType?: {[key: string]: NumberOfTransactionByType};
}
