/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PageDTO} from './page-dto';
import {PaymentCriteriaDTO} from './payment-criteria-dto';
import {SortDTO} from './sort-dto';

export interface SearchCriteriaDTOPaymentCriteriaDTO {
  page?: PageDTO;
  sort?: SortDTO;
  criteria?: PaymentCriteriaDTO;
}
