/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PageDTO} from './page-dto';
import {SortDTO} from './sort-dto';
import {AssetSearchCriteria} from './asset-search-criteria';

export interface SearchCriteriaDTOAssetSearchCriteria {
  page?: PageDTO;
  sort?: SortDTO;
  criteria?: AssetSearchCriteria;
}
