/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {EmissionFactorCriteriaDTO} from './emission-factor-criteria-dto';
import {PageDTO} from './page-dto';
import {SortDTO} from './sort-dto';

export interface SearchCriteriaDTOEmissionFactorCriteriaDTO {
  page?: PageDTO;
  sort?: SortDTO;
  criteria?: EmissionFactorCriteriaDTO;
}
