/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PageDTO} from './page-dto';
import {EmissionActivityCriteria} from './emission-activity-criteria';
import {SortDTO} from './sort-dto';

export interface SearchCriteriaDTOEmissionActivityCriteria {
  page?: PageDTO;
  sort?: SortDTO;
  criteria?: EmissionActivityCriteria;
}
