/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {ChemicalDensityCriteria} from './chemical-density-criteria';
import {PageDTO} from './page-dto';
import {SortDTO} from './sort-dto';

export interface SearchCriteriaDTOChemicalDensityCriteria {
  page?: PageDTO;
  sort?: SortDTO;
  criteria?: ChemicalDensityCriteria;
}
