/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PageDTO} from './page-dto';
import {SortDTO} from './sort-dto';
import {TransactionAdminCriteria} from './transaction-admin-criteria';

export interface SearchCriteriaDTOTransactionAdminCriteria {
  page?: PageDTO;
  sort?: SortDTO;
  criteria?: TransactionAdminCriteria;
}
