/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PageDTO} from './page-dto';
import {SortDTO} from './sort-dto';
import {EmissionActivityRecordCriteria} from './emission-activity-record-criteria';

export interface SearchCriteriaDTOEmissionActivityRecordCriteria {
  page?: PageDTO;
  sort?: SortDTO;
  criteria?: EmissionActivityRecordCriteria;
}
