/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SortDTO {
  field?: string;
  direction: SortDTO.DirectionEnum;
}
export namespace SortDTO {
  export const DirectionEnum = {
    ASC: 'ASC',
    DESC: 'DESC'
  } as const;
  export type DirectionEnum = (typeof DirectionEnum)[keyof typeof DirectionEnum];
}
