/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SubscribeRequestDTO {
  buildingId?: string;
  months?: number;
  numberOfDevices?: number;
  type?: SubscribeRequestDTO.TypeEnum;
}
export namespace SubscribeRequestDTO {
  export const TypeEnum = {
    NEW_PURCHASE: 'NEW_PURCHASE',
    UPGRADE: 'UPGRADE'
  } as const;
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
}
