/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {ActivityTypeDTO} from './activity-type-dto';
import {BuildingGroupDTO} from './building-group-dto';

export interface TenantDTO {
  id?: string;
  version?: number;
  buildingGroups?: Set<BuildingGroupDTO>;
  activityTypes?: Set<ActivityTypeDTO>;
  name?: string;
  email?: string;
  hotline?: string;
}
