/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TenantDetailDTO {
  id?: string;
  version?: number;
  name: string;
  email: string;
  address: string;
  hotline: string;
  taxCode: string;
  businessLicenseImageUrl?: string;
  representativeName?: string;
  representativePosition?: string;
  representativeContact?: string;
}
