/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {BuildingView} from './building-view';

export interface TenantTableView {
  id?: string;
  name?: string;
  email?: string;
  hotline?: string;
  buildings?: BuildingView[];
}
