/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TransactionDTO {
  id?: string;
  version?: number;
  createdDate?: string;
  amount?: number;
  months?: number;
  numberOfDevices?: number;
  transactionType?: TransactionDTO.TransactionTypeEnum;
}
export namespace TransactionDTO {
  export const TransactionTypeEnum = {
    NEW_PURCHASE: 'NEW_PURCHASE',
    UPGRADE: 'UPGRADE'
  } as const;
  export type TransactionTypeEnum = (typeof TransactionTypeEnum)[keyof typeof TransactionTypeEnum];
}
