/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UpdateUserLocale {
  language?: UpdateUserLocale.LanguageEnum;
}
export namespace UpdateUserLocale {
  export const LanguageEnum = {
    vi: 'vi',
    en: 'en',
    zh: 'zh'
  } as const;
  export type LanguageEnum = (typeof LanguageEnum)[keyof typeof LanguageEnum];
}
