spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: ${OIDC_CLIENT_ID}
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris: ${OIDC_REDIRECT_URI}
              post-logout-redirect-uris: ${OIDC_POST_LOGOUT_REDIRECT_URI}
              scopes:
                - openid
                - email
                - phone
            require-authorization-consent: false
            require-proof-key: true
  application:
    name: sep490-idp
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    default-schema: ${DB_SCHEMA}
    output-query-results: ${FLYWAY_OUTPUT_QUERIES:false}
    create-schemas: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  level:
    org:
      hibernate:
        SQL: ${HIBERNATE_SQL_LOG_LEVEL:INFO}
        type:
          descriptor:
            sql: ${HIBERNATE_SQL_PARAM_LOG_LEVEL:INFO}
