spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: ${OIDC_CLIENT_ID}
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris: ${OIDC_REDIRECT_URI}
              post-logout-redirect-uris: ${OIDC_POST_LOGOUT_REDIRECT_URI}
              scopes:
                - openid
                - email
                - phone
            require-authorization-consent: false
            require-proof-key: true
            token:
              access-token-time-to-live: PT1H
  mail:
    host: ${SMTP_HOST:127.0.0.1}
    port: ${SMTP_PORT:1025}
    username:
    password:
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: false
  application:
    name: sep490-idp
    homepage: http://localhost:4200
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    default-schema: ${DB_SCHEMA}
    output-query-results: ${FLYWAY_OUTPUT_QUERIES:false}
    create-schemas: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        query:
          fail_on_pagination_over_collection_fetch: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      auto-offset-reset: latest
      group-id: sep490-idp

logging:
  level:
    root: INFO
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:INFO}
        web: ${SPRING_WEB_LOG_LEVEL:INFO}
      hibernate:
        SQL: ${HIBERNATE_SQL_LOG_LEVEL:TRACE}
        type:
          descriptor:
            sql: ${HIBERNATE_SQL_PARAM_LOG_LEVEL:TRACE}
server:
  port: 8180
